#version: '3.8'
#
#services:
#  db:
#    image: postgres
#    container_name: postgres_container
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  app:
#    image: rutujapawase/farmdss_backend:latest
#    container_name: farmdss_backend_container
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farmdss
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#    depends_on:
#      - db
#    ports:
#      - '9001:9001'
#
#volumes:
#  postgres_data:
#    driver: local



#version: '3.8'
#
#services:
#  app:
#    image: username/my-spring-boot-app:latest
#    build:
#      context: .  # This assumes your Dockerfile is in the same directory as this docker-compose.yml
#      dockerfile: Dockerfile
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/farmdss
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_PROPERTIES_HIBERNATE_BOOT_ALLOW_JDBC_METADATA_ACCESS=false
#    ports:
#      - "9001:9001"
#
#  db:
#    image: postgres:latest
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=farmdss
#    ports:
#      - "5432:5432"


version: '3'
volumes:
  postgres_data:
    driver: local
services:
  farmdss:
    image: abhilash1809/farmdss:latest
    container_name: farmdss-backend-service
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/farmdss?currentSchema=public
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
    ports:
      - '9000:9000'

#version: '3'
#volumes:
#  postgres_data:
#    driver: local
#services:
#  db:
#    image: postgres:latest
#    container_name: postgres_container
#    restart: always
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_MAX_CONNECTIONS=1000
#    ports:
#      - '5432:5432'
#  farmdss:
#    image: rutujapawase/farmdss
#    container_name: farmdss-backend-service
#    environment:
#      - spring.datasource.url=jdbc:postgresql://db:5432/farmdss?currentSchema=public
#      - spring.datasource.username=postgres
#      - spring.datasource.password=postgres
#    ports:
#      - '8080:8080'

