spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/farmdss?currentSchema=public
#    url: jdbc:postgresql://52.66.188.149:5432/product?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false

  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        lob:
          non-contextual-creation: true
    show-sql: false
    open-in-view: false
    generate-ddl: false
    logging:
      level:
        org.hibernate: DEBUG
        org.springframework: DEBUG

server:
  port: 9001

